require:
  - rubocop-rspec_rails
  - rubocop-factory_bot

plugins:
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
    NewCops: enable
